name: Generate GitHub Snake Contribution

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Snake Contributions
        uses: Platane/snk@v3
        with:
          github_user_name: teqtinkerer

          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Commit and Push Changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

          git add dist/*
          git commit -m "Update GitHub Snake Contributions"
          git push
